# Site settings
title: Raphy BSU Blog
email: orelcokolov@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Кучка изобреталелей из восточной Европы
baseurl: "" # the subpath of your site, e.g. /blog/
url: https://raphy-bsu.github.io

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]

sass:
    sass_dir: _sass

gems: ["emoji_for_jekyll"]
